f = open(r'C:\Users\USER\Downloads\installable\lib\features\checkout\ui\sections\billing_section.dart', encoding='utf-8')
c = f.read()
f.close()
c = c.replace("label: 'Country',", "label: 'Address',")
c = c.replace("initialValue: gv('country'),", "initialValue: gv('address'),\n                  lines: 3,")
c = c.replace("vm.setRawField('country', v)", "vm.setRawField('address', v)")
c = c.replace("_ReadOnlyField(label: 'Country', value: u.country ?? '')", "_ReadOnlyField(label: 'Address', value: u.address ?? '', lines: 3)")
open(r'C:\Users\USER\Downloads\installable\lib\features\checkout\ui\sections\billing_section.dart', 'w', encoding='utf-8').write(c)
print('done')
