// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlFNavo7Ou2jHlaaoDl26Jlt0FdxL_4zA',
    appId: '1:971585536390:web:24fb580457c5df0e542c07',
    messagingSenderId: '971585536390',
    projectId: 'ticbook-e7934',
    authDomain: 'ticbook-e7934.firebaseapp.com',
    storageBucket: 'ticbook-e7934.firebasestorage.app',
    measurementId: 'G-EKN4K76ZMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8YAC_h-sU2ejTttZHKJwLM7hKq6K9ZnA',
    appId: '1:971585536390:android:39cfcd16f7436840542c07',
    messagingSenderId: '971585536390',
    projectId: 'ticbook-e7934',
    storageBucket: 'ticbook-e7934.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxHlNdYCjVbGPNfHiJcAdLlCWuHpZlGqQ',
    appId: '1:971585536390:ios:53e21352e9b33d62542c07',
    messagingSenderId: '971585536390',
    projectId: 'ticbook-e7934',
    storageBucket: 'ticbook-e7934.firebasestorage.app',
    iosClientId: '971585536390-47jidblsu9blo9pfbahc4p15ojstvlg4.apps.googleusercontent.com',
    iosBundleId: 'com.ticbook.ticbookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxHlNdYCjVbGPNfHiJcAdLlCWuHpZlGqQ',
    appId: '1:971585536390:ios:53e21352e9b33d62542c07',
    messagingSenderId: '971585536390',
    projectId: 'ticbook-e7934',
    storageBucket: 'ticbook-e7934.firebasestorage.app',
    iosClientId: '971585536390-47jidblsu9blo9pfbahc4p15ojstvlg4.apps.googleusercontent.com',
    iosBundleId: 'com.ticbook.ticbookapp',
  );

}